### ISSUE TITLE
Swift package plugin doesn't pick up `.prefire.yml`

### ISSUE THREAD

**Issue by markst** [BarredEwe/Prefire#10]
I've placed a `.prefire.yml` in multiple places up the directory chain.

**Comment by BarredEwe** [comment]
Hello! Thanks for finding the issue 😊

Can you attach this information?
- path to `.prefire.yml` file
- path to xcode project
- path to `Package.swift`
- path to target where Prefire is launched

**Comment by BarredEwe** [comment]
I have added additional build information https://github.com/BarredEwe/Prefire/pull/13. It may help to find the problem.

**Comment by markst** [comment]
Thanks, I'll have another go. Though my fix seems to be working fine now. Using `URL(fileURLWithPath` rather than interpolation.

**Comment by BarredEwe** [comment]
Thanks, I've already added your fix to [the latest version](https://github.com/BarredEwe/Prefire/releases/tag/1.0.3 ).

I think, I can close this issue 😊

**Comment by BarredEwe** [comment]
Thanks, I've already added your fix to [the latest version](https://github.com/BarredEwe/Prefire/releases/tag/1.0.3 ).

I think, I can close this issue 😊
