### ISSUE TITLE
Xcode 15 NSCocoaError 513

### ISSUE THREAD

**Issue by Velin92** [BarredEwe/Prefire#24]
When I try to run my tests on Xcode 15 with the PrefireTestsPlugin I get the following error:
<img width="772" alt="Screenshot 2023-09-19 at 10 45 51" src="https://github.com/BarredEwe/Prefire/assets/34335419/09d75687-ff58-4890-97c1-b5ba508af204">

I am using a custom prefire config file where I write the tests in an internal folder of the project tests

**Comment by BarredEwe** [comment]
**Xcode 15** does not give plugins permission to write to the project directory 🥲

As a quick solution, I can recommend writing in **DerivedData**. 
To do this, remove the `test_file_path` parameter from the `.prefier.yml` file.

Now I'm trying to find another solution, but so far there are difficulties with this. To be honest, I'm not sure that it can be possible now: https://github.com/apple/swift-package-manager/issues/6814

**Comment by Velin92** [comment]
I see.
I tried your suggested solution, to just use the DerivedData, by removing the test_file_path, however the UnitTests do not build since multiple commands seem to be produce the UnitTest product.

Do you know what might be causing this issue?

```
Prepare build
note: Building targets in dependency order
error: Multiple commands produce '/Users/mauroromito/Library/Developer/Xcode/DerivedData/ElementX-aywdboxrhlkajqbvczulivesmexq/Build/Products/Debug-iphonesimulator/ElementX.app/PlugIns/UnitTests.xctest/UnitTests'
    note: Target 'UnitTests' (project 'ElementX') has copy command from '/Users/mauroromito/Library/Developer/Xcode/DerivedData/ElementX-aywdboxrhlkajqbvczulivesmexq/SourcePackages/plugins/ElementX.output/UnitTests/PrefireTestsPlugin/UnitTests' to '/Users/mauroromito/Library/Developer/Xcode/DerivedData/ElementX-aywdboxrhlkajqbvczulivesmexq/Build/Products/Debug-iphonesimulator/ElementX.app/PlugIns/UnitTests.xctest/UnitTests'
    note: Target 'UnitTests' (project 'ElementX') has link command with output '/Users/mauroromito/Library/Developer/Xcode/DerivedData/ElementX-aywdboxrhlkajqbvczulivesmexq/Build/Products/Debug-iphonesimulator/ElementX.app/PlugIns/UnitTests.xctest/UnitTests'


Building targets in dependency order

Multiple commands produce '/Users/mauroromito/Library/Developer/Xcode/DerivedData/ElementX-aywdboxrhlkajqbvczulivesmexq/Build/Products/Debug-iphonesimulator/ElementX.app/PlugIns/UnitTests.xctest/UnitTests'

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: 4f8dec47da3429f29502ac0dae87d55d
Build description path: /Users/mauroromito/Library/Developer/Xcode/DerivedData/ElementX-aywdboxrhlkajqbvczulivesmexq/Build/Intermediates.noindex/XCBuildData/4f8dec47da3429f29502ac0dae87d55d.xcbuilddata


```

**Comment by BarredEwe** [comment]
Could you try the [latest release](https://github.com/BarredEwe/Prefire/releases/tag/1.5.0)?

**Comment by Velin92** [comment]
Tried, and it now works thanks!
However having the code in the DerivedData has some downsides (sometimes the code does not preview, you cannot directly change it to play around with it, which makes editing the stencil a bit more painful).

Instead of generating the code through the plugin, would be possible to instead expose/use a command that we may run during the Build Phase of the app?
I guess this should allow for changes indie the project directory itself.
