### ISSUE TITLE
Device/Height independent Tests

### ISSUE THREAD

**Issue by Velin92** [BarredEwe/Prefire#26]
Would be nice to have the preview of the tests be device or height independent in some way.
What I mean is that it seems that there is no way to generate the previews so that they match exactly their fitting size.
This would be very useful to render scroll views for example, or very huge vertical stack layouts that do not fit a single iPhone screen.
Maybe the test code could only pick the device width (and not be completely device independent), and then have the height get rendered based on a size that fits it.
Or maybe in the configuration you could specify a specific device width (either from a device family like iPhone X or giving the px/pts value directly).

I am actually playing around myself with the .stencil code to see if I can achieve something like that but so far I did not find a solution that works generally.

**Comment by BarredEwe** [comment]
Hi!

The dynamic height can be set using the standard function in preview:
```swift
.previewLayout(.sizeThatFits)
```

Here is an example:
```swift
struct TestView_Preview: PreviewProvider, PrefireProvider {
    static var previews: some View {
        VStack {
            ForEach(0..<60) { _ in
                Text("Test")
            }
        }
        .previewLayout(.sizeThatFits)
    }
}
```
<details>
<summary>And here is the result:</summary>
<img src="https://github.com/BarredEwe/Prefire/assets/19188911/b25e80ae-712b-44ba-8d4a-963d388e12c9" width="250">
</details>
