### ISSUE TITLE
Regression when specifying a `template_file_path`

### ISSUE THREAD

**Issue by stefanceriu** [BarredEwe/Prefire#37]
## Context 🕵️‍♀️
Setup the Prefire example project to use a  `- template_file_path: PreviewTests.stencil`, where `PreviewTests.stencil` is just a copy of the default template next to `PreFireExample.xcodeproj` 

## What 🌱
Specifying a `template_file_path` doesn't seem to be working anymore resulting in a `does not exist or is not readable` error

## Proposal 🎉
Let's try to fix it maybe 😁

**Comment by stefanceriu** [comment]
Okay, so the problem seems to be that the Prefire binary isn't aware of what the right path should be. I've managed to get it working [here](https://github.com/stefanceriu/Prefire/commit/9ae4206caf1fed9cc2cf357f7a5a8497f8d1a414) piggybacking on the config file URL but perhaps you have an idea for a cleaner solution.

**Comment by BarredEwe** [comment]
Fixed in: https://github.com/BarredEwe/Prefire/pull/39

**Comment by stefanceriu** [comment]
This might help, the configuration isn't picked up when running directly through `xcodebuild` either

`xcodebuild -project 'PreFireExample.xcodeproj' -scheme 'PrefireExample'  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' test`

**Comment by stefanceriu** [comment]
I got it working by using `URL(filePath:)` to build correct file paths but it's clear that the `ConfigPathBuilder` needs tweaking. I would suggest rewriting it to use URls instead of direct string manipulation.

```diff
     static func load(from configPath: String?, testTargetPath: String?, verbose: Bool) -> Config? {
-        let possibleConfigPaths = ConfigPathBuilder.possibleConfigPaths(for: configPath, testTargetPath: testTargetPath)
+        var possibleConfigPaths = [String]()
+
+        if let configPath {
+            possibleConfigPaths = [URL(filePath: configPath).appending(path: ".prefire.yml").path()]
+        }

         for path in possibleConfigPaths {
-            guard let configUrl = URL(string: Constants.fileMark + path),
-                  FileManager.default.fileExists(atPath: configUrl.path),
+
+            let configUrl = URL(filePath: path)
+
+            print("🟢 Checking url: \(configUrl)")
+
+            guard FileManager.default.fileExists(atPath: configUrl.path),
                   let configDataString = try? String(contentsOf: configUrl, encoding: .utf8) else { continue }

             if verbose {
```

```
🟢 Checking url: file:///Users/stefanceriu/Developer/Prefire/Example/.prefire.yml
🟢 The '.prefire' file is used on the path: /Users/stefanceriu/Developer/Prefire/Example/.prefire.yml
```

vs what the current version does

```
🟡 The '.prefire' file was not found by paths:
  - /Users/stefanceriu/Developer/Prefire/Example/PrefireExampleTests/.prefire.yml
  - Users/stefanceriu/Developer/Prefire/Example/.prefire.yml
  - /Users/stefanceriu/Developer/Prefire/Example/Users/stefanceriu/Developer/Prefire/Example/.prefire.yml
  ```
