### ISSUE TITLE
Xcode 15.3 - Plug-in ended with uncaught signal: 5)

### ISSUE THREAD

**Issue by woutergoossens** [BarredEwe/Prefire#41]
## Context 🕵️‍♀️
Hi,

I updated to Xcode 15.3 and when I want to run my preview tests again I get `Plug-in ended with uncaught signal: 5)`
<img width="1454" alt="Screenshot 2024-03-07 at 12 00 12" src="https://github.com/BarredEwe/Prefire/assets/355048/00f1cf3e-58f6-465e-876f-098e21255ff9">

If you need more information or logs, please let me know.
Thanks

**Comment by BarredEwe** [comment]
I'll install a new Xcode and try to figure it out 🤔

**Comment by BarredEwe** [comment]
Apparently, this is [a problem with Xcode](https://forums.developer.apple.com/forums/thread/740567). 
It is solved like this: `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by BarredEwe** [comment]
I posted a fix in the [new release](https://github.com/BarredEwe/Prefire/releases/tag/2.0.4). You can already try it!

**Comment by woutergoossens** [comment]
Thanks! But still waiting for https://github.com/BarredEwe/Prefire/pull/36 before I can update to a new release.. :)
