### ISSUE TITLE
how to custom snapshot image file name?

### ISSUE THREAD

**Issue by bill-florio** [BarredEwe/Prefire#69]
## Context 🕵️‍♀️
I would like to custom the snapshot image file name with custom prefix. e.g. with Swift snapshot testing, I can change the file name like `test_snapshots.EU-staging-pt_PT`

## What 🌱
I checked `PreviewTests.stencil`, and found the file name is created from `preview.displayName`. Here is my code to do it with swift snapshot testing

```
            .assertSnapshots(as: .image(precision: precision,
                                        layout: .device(config: config)),
                             named: LocaleHelper.deviceLanguage + "_" + LocaleHelper.regionCode,
                             record: recording,
                             snapshotDirectory: XCTestCase.snapshotDirectoryUrl(file: file, pathPrefix: pathPrefix).path,
                             file: file,
                             testName: testName,
                             line: line
            )
   ```

## Proposal 🎉
I am thinking about editing `PreviewTests.stencil`, or add a new option to allow custom prefix?

**Comment by BarredEwe** [comment]
Hi! I apologize for the long reply. You can change the name using the standard preview parameters. 
For example:
```swift
#Preview("SomeName") {
    Text("TestView")
}
```
or 
```swift
struct TestView_Previews: PrefireProvider {
    Text("TestView")
        .previewDisplayName("SomeName")
}
```

**Comment by BarredEwe** [comment]
If you want to change `PreviewTest.stencil`, you can copy the current one to yourself and change it. Then put the parameter in `prefire.yml`:
```yaml
test_configuration:
  - test_file_path: PrefireExampleTests/PreviewTests.generated.swift
 ```
