### ISSUE TITLE
Wrong preview image names

### ISSUE THREAD

**Issue by woutergoossens** [BarredEwe/Prefire#77]
## Context 🕵️‍♀️
I updated Prefire from 2.8.0 to 3.0.0 and it seems the names of the preview images are changed?
I also could reproduce it with the Example app

## What 🌱
It generates an image name like "test_authView_Preview-iPad.PreviewTests-test_authView_Preview.png"
But I would expect "test_authView_Preview-iPad.png"?
It seems it re-uses the test function name again?

<img width="600" alt="Screenshot 2024-12-04 at 08 40 11" src="https://github.com/user-attachments/assets/ac02082d-1997-4d40-8c6e-670128558ef3">

**Comment by BarredEwe** [comment]
Thanks a lot for finding the problem, put the fix in the new release!
https://github.com/BarredEwe/Prefire/releases/tag/3.0.1

**Comment by woutergoossens** [comment]
Thanks for the fast fix. Tested and working. Keep up the good work! 🥳
