### ISSUE TITLE
Cannot find 'file' in scope

### ISSUE THREAD

**Issue by markst** [BarredEwe/Prefire#8]
Seems that `StaticString` is conditional of `argument.file` but the `assertSnapshot` argument condition is not resolving correctly.

**Comment by BarredEwe** [comment]
Hello! Thanks for finding the issue 😊

Could you attach this information?
- path to `.prefire.yml`
- path to xcode project
- path to `Package.swift`
- path to target where Prefire is launched

**Comment by markst** [comment]
Might be good to use the `preview?.displayName` as fallback?

**Comment by BarredEwe** [comment]
> Might be good to use the `preview?.displayName` as fallback?
Can you add some example?
